name: network_core
description: Network core package
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  http: ^1.1.0
  network_extensions:
    path: ../extensions

dev_dependencies:
  lint_commons:
    path: ../../lint
  test: ^1.24.9
