name: commons_testing
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  ds:
    path: ../../ds
  path: ^1.8.0
  http: ^1.1.0
  test: ^1.21.0
  alchemist: ^0.7.0
  golden_toolkit: ^0.15.0

dev_dependencies:
  lints: ^2.0.0
