root: true
extends: standard
env:
  commonjs: true
  es2021: true
  node: true
parserOptions:
  ecmaVersion: latest
rules:
  semi:
    - warn
    - never
  comma-dangle:
    - warn
    - always-multiline