name: ds
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.1.3 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/generic_error.svg

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
          style: normal
          weight: 400
